-------------------------------------------------------------------------------
Test set: com.challengeBackend.techforb.UserServiceTests
-------------------------------------------------------------------------------
Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 1.072 s <<< FAILURE! - in com.challengeBackend.techforb.UserServiceTests
testRealizarTransferenciaSaldoSuficienteTransaccionExitosa  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: com.challengeBackend.techforb.models.Transaccion.usuarioRemitente in com.challengeBackend.techforb.models.User.transacciones
Caused by: org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: com.challengeBackend.techforb.models.Transaccion.usuarioRemitente in com.challengeBackend.techforb.models.User.transacciones

testAddTarjetaAJohn  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: com.challengeBackend.techforb.models.Transaccion.usuarioRemitente in com.challengeBackend.techforb.models.User.transacciones
Caused by: org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: com.challengeBackend.techforb.models.Transaccion.usuarioRemitente in com.challengeBackend.techforb.models.User.transacciones

testExtraerDinero_SaldoSuficiente  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: com.challengeBackend.techforb.models.Transaccion.usuarioRemitente in com.challengeBackend.techforb.models.User.transacciones
Caused by: org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: com.challengeBackend.techforb.models.Transaccion.usuarioRemitente in com.challengeBackend.techforb.models.User.transacciones

guardarUsuario  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: com.challengeBackend.techforb.models.Transaccion.usuarioRemitente in com.challengeBackend.techforb.models.User.transacciones
Caused by: org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: com.challengeBackend.techforb.models.Transaccion.usuarioRemitente in com.challengeBackend.techforb.models.User.transacciones

testIngresarDinero_SaldoSuficiente  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: com.challengeBackend.techforb.models.Transaccion.usuarioRemitente in com.challengeBackend.techforb.models.User.transacciones
Caused by: org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: com.challengeBackend.techforb.models.Transaccion.usuarioRemitente in com.challengeBackend.techforb.models.User.transacciones

